/* ESQUEMA */
USE GD2C2016;
GO

CREATE SCHEMA FLOPANICMA AUTHORIZATION GD;
GO

/**************/
/* SECUENCIAS */
/**************/

CREATE SEQUENCE FLOPANICMA.AFILIADO_SEQ START WITH 100 INCREMENT BY 100;
CREATE SEQUENCE FLOPANICMA.MATRICULA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FLOPANICMA.PERSONA_SEQ	START WITH 1 INCREMENT BY 1;


/**********/
/* TABLAS */
/**********/

CREATE TABLE FLOPANICMA.PERSONA
(
		ID_PERSONA INT NOT NULL PRIMARY KEY,
		NOMBRE VARCHAR(255) NULL,
		APELLIDO VARCHAR(255) NULL,
		DIRECCION VARCHAR(255) NULL,
		TELEFONO NUMERIC(18,0) NULL,
		E_MAIL VARCHAR(255) NOT NULL DEFAULT 'SIN E-MAIL',
		F_NACIMIENTO DATETIME NULL,
		TIPO_DOCUMENTO VARCHAR(20) NOT NULL DEFAULT 'DNI',
		NRO_DOCUMENTO NUMERIC(18,0) NULL,
		SEXO VARCHAR(1) NULL,
);

CREATE TABLE FLOPANICMA.PROFESIONAL
(
		ID_PROFESIONAL INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		ID_PERSONA INT NOT NULL,
		MATRICULA INT NOT NULL,
		HORAS_ACUMULADAS INT NOT NULL DEFAULT 0,
		
		CONSTRAINT FK_PROFESIONAL_PERSONA FOREIGN KEY (ID_PERSONA) REFERENCES FLOPANICMA.PERSONA(ID_PERSONA)
);

CREATE TABLE FLOPANICMA.AGENDA
(		
		ID_PROFESIONAL INT NOT NULL PRIMARY KEY,
		PERIODO_INICIO DATE NOT NULL,
		PERIODO_FIN DATE NOT NULL,
		
		CONSTRAINT FK_AGENDA_PROFESIONAL FOREIGN KEY (ID_PROFESIONAL) REFERENCES FLOPANICMA.PROFESIONAL(ID_PROFESIONAL)
);

CREATE TABLE FLOPANICMA.TIPO_ESPECIALIDAD
(
		ID_TIPO_ESPECIALIDAD NUMERIC(18,0) NOT NULL PRIMARY KEY,
		DETALLE VARCHAR(255) NULL
);

CREATE TABLE FLOPANICMA.ESPECIALIDAD
(
		ID_ESPECIALIDAD NUMERIC(18,0) NOT NULL PRIMARY KEY,
		ID_TIPO_ESPECIALIDAD NUMERIC(18,0) NOT NULL,
		DETALLE VARCHAR(255) NULL,
		
		CONSTRAINT FK_ESPECIALIDAD_TIPO_ESPECIALIDAD FOREIGN KEY (ID_TIPO_ESPECIALIDAD) REFERENCES FLOPANICMA.TIPO_ESPECIALIDAD(ID_TIPO_ESPECIALIDAD)
);

CREATE TABLE FLOPANICMA.ACTIVIDAD_DIA
(
		ID_PROFESIONAL INT NOT NULL,
		DIA VARCHAR(10) NOT NULL, 
		HORA_INICIO TIME(0) NOT NULL,
		HORA_FIN TIME(0) NOT NULL,
		ID_ESPECIALIDAD NUMERIC (18,0) NOT NULL,
		
		CONSTRAINT PK_ACTIVIDAD_DIA PRIMARY KEY(ID_PROFESIONAL,DIA,HORA_INICIO,HORA_FIN),
		CONSTRAINT FK_ACTIVIDAD_DIA_AGENDA FOREIGN KEY (ID_PROFESIONAL) REFERENCES FLOPANICMA.AGENDA(ID_PROFESIONAL),
		CONSTRAINT FK_ACTIVIDAD_DIA_ESPECIALIDAD FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES FLOPANICMA.ESPECIALIDAD(ID_ESPECIALIDAD)
);

CREATE TABLE FLOPANICMA.PLAN_MEDICO
(
		ID_PLAN NUMERIC(18,0) NOT NULL PRIMARY KEY,
		DESCRIPCION VARCHAR(255)NULL,
		CUOTA NUMERIC(18,0) NULL,
		COSTO_CONSULTA NUMERIC(18,0) NULL,
		COSTO_FARMACIA NUMERIC(18,0) NULL
);

CREATE TABLE FLOPANICMA.AFILIADO
(
		ID_AFILIADO INT NOT NULL PRIMARY KEY,
		PLAN_MEDICO NUMERIC(18,0) NOT NULL,
		ACTIVO BIT NOT NULL DEFAULT 1,
		ESTADO_CIVIL VARCHAR(50) NOT NULL DEFAULT 'SOLTERO/A',
		CANTIDAD_HIJOS INT NOT NULL DEFAULT 0,
		NRO_CONSULTA INT NOT NULL DEFAULT 0, --DE MOMENTO HASTA ENTENDER EL ENUNCIADO!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
		ID_PERSONA INT NOT NULL,
		
		CONSTRAINT FK_AFILIADO_PLAN_MEDICO FOREIGN KEY (PLAN_MEDICO) REFERENCES FLOPANICMA.PLAN_MEDICO(ID_PLAN),
		CONSTRAINT FK_AFILIADO_PERSONA FOREIGN KEY (ID_PERSONA) REFERENCES FLOPANICMA.PERSONA(ID_PERSONA)
);

CREATE TABLE FLOPANICMA.BONOS
(
		ID_OPERACION INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		PLAN_MEDICO NUMERIC(18,0) NOT NULL,
		NUMERO_AFILIADO INT NOT NULL,
		CANTIDAD_BONOS INT,
		
		CONSTRAINT FK_BONOS_PLAN_MEDICO FOREIGN KEY (PLAN_MEDICO) REFERENCES FLOPANICMA.PLAN_MEDICO(ID_PLAN),
		CONSTRAINT FK_BONOS_AFILIADO FOREIGN KEY (NUMERO_AFILIADO) REFERENCES FLOPANICMA.AFILIADO(ID_AFILIADO)
);

CREATE TABLE FLOPANICMA.MODIFICACIONES
(
		ID_MODIFICACION INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		ID_AFILIADO INT NOT NULL,
		FECHA DATE NOT NULL,
		DETALLE VARCHAR(255) NOT NULL,
		PLAN_MEDICO_ANTERIOR NUMERIC(18,0) NOT NULL,
		
		CONSTRAINT FK_MODIFICACIONES_AFILIADO FOREIGN KEY (ID_AFILIADO) REFERENCES FLOPANICMA.AFILIADO(ID_AFILIADO),
		CONSTRAINT FK_MODIFICACIONES_PLAN_MEDICO FOREIGN KEY (PLAN_MEDICO_ANTERIOR) REFERENCES FLOPANICMA.PLAN_MEDICO(ID_PLAN)
);

CREATE TABLE FLOPANICMA.ESPECIALIDAD_PROFESIONAL
(
		ID_PROFESIONAL INT NOT NULL,
		ID_ESPECIALIDAD NUMERIC(18,0) NOT NULL,
		
		CONSTRAINT PK_ESPECIALIDAD_PROFESIONAL PRIMARY KEY (ID_PROFESIONAL,ID_ESPECIALIDAD),
		CONSTRAINT FK_ESPECIALIDAD_PROFESIONAL_ESPECIALIDAD FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES FLOPANICMA.ESPECIALIDAD(ID_ESPECIALIDAD),
		CONSTRAINT FK_ESPECIALIDAD_PROFESIONAL_PROFESIONAL FOREIGN KEY (ID_PROFESIONAL) REFERENCES FLOPANICMA.PROFESIONAL(ID_PROFESIONAL)
);

CREATE TABLE FLOPANICMA.TIPO_CANCELACION
(
		ID_TIPO_CANCELACION INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
		DETALLE VARCHAR(255) NULL
);

CREATE TABLE FLOPANICMA.CANCELACIONES
(
		ID_CANCELACION INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		COD_TIPO_CANCELACION INT NOT NULL,
		
		CONSTRAINT FK_CANCELACION_TIPO_CANCELACION FOREIGN KEY (COD_TIPO_CANCELACION) REFERENCES FLOPANICMA.TIPO_CANCELACION(ID_TIPO_CANCELACION)
);

CREATE TABLE FLOPANICMA.CONSULTAS
(
		ID_CONSULTA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		ID_PROFESIONAL INT NOT NULL,
		ID_AFILIADO INT NOT NULL,
		DIA DATE NOT NULL,
		HORA TIME(0) NOT NULL,
		SINTOMA VARCHAR(255) NOT NULL,
		DIAGNOSTICO VARCHAR(255) NOT NULL,
		
		CONSTRAINT FK_CONSULTAS_AFILIADO FOREIGN KEY (ID_AFILIADO) REFERENCES FLOPANICMA.AFILIADO(ID_AFILIADO),
		CONSTRAINT FK_CONSULTAS_PROFESIONAL FOREIGN KEY (ID_PROFESIONAL) REFERENCES FLOPANICMA.PROFESIONAL(ID_PROFESIONAL)
);

CREATE TABLE FLOPANICMA.FUNCIONALIDAD
(
		ID_FUNCIONALIDAD INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		DESCRIPCION VARCHAR(255),
);

CREATE TABLE FLOPANICMA.PEDIDO_TURNO
(
		ID_PEDIDO NUMERIC(18,0) IDENTITY(1,1) NOT NULL PRIMARY KEY,
		FECHA DATE NOT NULL,
		HORARIO TIME(0) NOT NULL,
		ID_PROFESIONAL INT NOT NULL,
		ID_AFILIADO INT NOT NULL,
		ID_CANCELACION INT NULL,
		
		CONSTRAINT FK_PEDIDO_TURNO_PROFESIONAL FOREIGN KEY (ID_PROFESIONAL) REFERENCES FLOPANICMA.PROFESIONAL(ID_PROFESIONAL),
		CONSTRAINT FK_PEDIDO_TURNO_AFILIADO FOREIGN KEY (ID_AFILIADO) REFERENCES FLOPANICMA.AFILIADO(ID_AFILIADO),
		CONSTRAINT FK_PEDIDO_TURNO_CANCELACIONES FOREIGN KEY (ID_CANCELACION) REFERENCES FLOPANICMA.CANCELACIONES(ID_CANCELACION)
);

CREATE TABLE FLOPANICMA.ROL
(
		ID_ROL INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		DESCRIPCION VARCHAR(255) NULL,
		ACTIVO BIT NOT NULL
);

CREATE TABLE FLOPANICMA.USUARIO
(
		ID_USUARIO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		ID_PERSONA INT NOT NULL,
		USERNAME VARCHAR(50) NOT NULL,
		PASSWORD VARCHAR(50) NOT NULL,
		INTENTOS INT NOT NULL DEFAULT 0,
		ACTIVO BIT NOT NULL DEFAULT 1,
		
		CONSTRAINT FK_USUARIO_PERSONA FOREIGN KEY(ID_PERSONA) REFERENCES FLOPANICMA.PERSONA(ID_PERSONA)
);

CREATE TABLE FLOPANICMA.USUARIO_ROL
(
		ID_USUARIO INT NOT NULL,
		ID_ROL INT NOT NULL,
		
		CONSTRAINT PK_USUARIO_ROL PRIMARY KEY (ID_USUARIO,ID_ROL),
		CONSTRAINT FK_USUARIO_ROL_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES FLOPANICMA.USUARIO(ID_USUARIO),
		CONSTRAINT FK_USUARIO_ROL_ROL FOREIGN KEY (ID_ROL) REFERENCES FLOPANICMA.ROL(ID_ROL)
);

CREATE TABLE FLOPANICMA.ROL_FUNCIONALIDAD
(
		ID_ROL INT NOT NULL,
		ID_FUNCIONALIDAD INT NOT NULL,
		
		CONSTRAINT PK_ROL_FUNCIONALIDAD PRIMARY KEY (ID_ROL,ID_FUNCIONALIDAD),
		CONSTRAINT FK_ROL_FUNCIONALIDAD_ROL FOREIGN KEY (ID_ROL) REFERENCES FLOPANICMA.ROL(ID_ROL),
		CONSTRAINT FK_ROL_FUNCIONALIDAD_FUNCIONALIDAD FOREIGN KEY (ID_FUNCIONALIDAD) REFERENCES FLOPANICMA.FUNCIONALIDAD(ID_FUNCIONALIDAD)
);


/***********/
/* INDICES */
/***********/
CREATE UNIQUE INDEX NRO_DOCUMENTO_IND1 ON FLOPANICMA.PERSONA(NRO_DOCUMENTO);
CREATE UNIQUE INDEX USUARIO_IND1 ON FLOPANICMA.USUARIO(USERNAME);


/***********************/
/* INSERTS DATOS FIJOS */
/***********************/



/************/
/* MIGRADOR */
/************/
GO

/*INSERTAR DATOS FIJOS*/
CREATE PROCEDURE FLOPANICMA.Z_MIGRACION_INSERT_DATOS_FIJOS
AS
BEGIN
	
	/*FLOPANICMA.ROL*/
	INSERT INTO FLOPANICMA.ROL(DESCRIPCION,ACTIVO)
	VALUES
	('ADMINISTRATIVO',1),
	('PROFESIONAL',1),
	('AFILIADO',1),
	('ADMINISTRADOR',1);
	
	/*FLOPANICMA.FUNCIONALIDAD*/
	INSERT INTO FLOPANICMA.FUNCIONALIDAD(DESCRIPCION)
	VALUES
	('ABM DE AFILIADO'),
	('ABM DE ESPECIALIDADES MEDICAS'),
	('ABM DE PLANES MEDICOS'),
	('ABM DE PROFESIONAL'),
	('ABM DE ROL'),
	('CANCELAR ATENCION'),
	('COMPRA DE BONOS'),
	('LISTADOS'),
	('PEDIR TURNO'),
	('REGISTRAR AGENDA PROFESIONAL'),
	('REGISTRAR LLEGADA'),
	('REGISTRAR RESULTADO');
	
	/*FLOPLANICMA.ROL_FUNCIONALIDAD*/
	DECLARE @ID_ROL INT;
	
	/*FUNCIONALIDADES DEL ROL ADMINISTRATIVO*/
	SELECT @ID_ROL = ID_ROL FROM FLOPANICMA.ROL WHERE DESCRIPCION='ADMINISTRATIVO';
	INSERT INTO FLOPANICMA.ROL_FUNCIONALIDAD (ID_ROL,ID_FUNCIONALIDAD)
	VALUES
	(@ID_ROL,(SELECT ID_FUNCIONALIDAD FROM FLOPANICMA.FUNCIONALIDAD WHERE DESCRIPCION = 'ABM DE AFILIADO')),
	(@ID_ROL,(SELECT ID_FUNCIONALIDAD FROM FLOPANICMA.FUNCIONALIDAD WHERE DESCRIPCION = 'ABM DE ESPECIALIDADES MEDICAS')),
	(@ID_ROL,(SELECT ID_FUNCIONALIDAD FROM FLOPANICMA.FUNCIONALIDAD WHERE DESCRIPCION ='ABM DE PLANES MEDICOS')),
	(@ID_ROL,(SELECT ID_FUNCIONALIDAD FROM FLOPANICMA.FUNCIONALIDAD WHERE DESCRIPCION ='ABM DE PROFESIONAL')),
	(@ID_ROL,(SELECT ID_FUNCIONALIDAD FROM FLOPANICMA.FUNCIONALIDAD WHERE DESCRIPCION ='ABM DE ROL')),
	(@ID_ROL,(SELECT ID_FUNCIONALIDAD FROM FLOPANICMA.FUNCIONALIDAD WHERE DESCRIPCION ='REGISTRAR LLEGADA'));
	
	/*FUNCIONALIDADES DEL ROL AFILIADO*/
	SELECT @ID_ROL = ID_ROL FROM FLOPANICMA.ROL WHERE DESCRIPCION='AFILIADO';
	INSERT INTO FLOPANICMA.ROL_FUNCIONALIDAD (ID_ROL,ID_FUNCIONALIDAD)
	VALUES
	(@ID_ROL,(SELECT ID_FUNCIONALIDAD FROM FLOPANICMA.FUNCIONALIDAD WHERE DESCRIPCION ='CANCELAR ATENCION')),
	(@ID_ROL,(SELECT ID_FUNCIONALIDAD FROM FLOPANICMA.FUNCIONALIDAD WHERE DESCRIPCION ='COMPRA DE BONOS')),
	(@ID_ROL,(SELECT ID_FUNCIONALIDAD FROM FLOPANICMA.FUNCIONALIDAD WHERE DESCRIPCION ='PEDIR TURNO'));
	
	/*FUNCIONALIDADES DEL ROL PROFESIONAL*/
	SELECT @ID_ROL = ID_ROL FROM FLOPANICMA.ROL WHERE DESCRIPCION='PROFESIONAL';
	INSERT INTO FLOPANICMA.ROL_FUNCIONALIDAD (ID_ROL,ID_FUNCIONALIDAD)
	VALUES
	(@ID_ROL,(SELECT ID_FUNCIONALIDAD FROM FLOPANICMA.FUNCIONALIDAD WHERE DESCRIPCION ='REGISTRAR AGENDA PROFESIONAL')),
	(@ID_ROL,(SELECT ID_FUNCIONALIDAD FROM FLOPANICMA.FUNCIONALIDAD WHERE DESCRIPCION ='CANCELAR ATENCION')),
	(@ID_ROL,(SELECT ID_FUNCIONALIDAD FROM FLOPANICMA.FUNCIONALIDAD WHERE DESCRIPCION ='REGISTRAR RESULTADO'));
	
	/*FUNCIONALIDADES DEL ROL ADMINISTRADOR*/
	SELECT @ID_ROL = ID_ROL FROM FLOPANICMA.ROL WHERE DESCRIPCION='ADMINISTRADOR';
	INSERT INTO FLOPANICMA.ROL_FUNCIONALIDAD(ID_ROL,ID_FUNCIONALIDAD)
	VALUES
	(@ID_ROL,(SELECT ID_FUNCIONALIDAD FROM FLOPANICMA.FUNCIONALIDAD WHERE DESCRIPCION = 'ABM DE AFILIADO')),
	(@ID_ROL,(SELECT ID_FUNCIONALIDAD FROM FLOPANICMA.FUNCIONALIDAD WHERE DESCRIPCION = 'ABM DE ESPECIALIDADES MEDICAS')),
	(@ID_ROL,(SELECT ID_FUNCIONALIDAD FROM FLOPANICMA.FUNCIONALIDAD WHERE DESCRIPCION ='ABM DE PLANES MEDICOS')),
	(@ID_ROL,(SELECT ID_FUNCIONALIDAD FROM FLOPANICMA.FUNCIONALIDAD WHERE DESCRIPCION ='ABM DE PROFESIONAL')),
	(@ID_ROL,(SELECT ID_FUNCIONALIDAD FROM FLOPANICMA.FUNCIONALIDAD WHERE DESCRIPCION ='ABM DE ROL')),
	(@ID_ROL,(SELECT ID_FUNCIONALIDAD FROM FLOPANICMA.FUNCIONALIDAD WHERE DESCRIPCION ='REGISTRAR LLEGADA')),
	(@ID_ROL,(SELECT ID_FUNCIONALIDAD FROM FLOPANICMA.FUNCIONALIDAD WHERE DESCRIPCION ='CANCELAR ATENCION')),
	(@ID_ROL,(SELECT ID_FUNCIONALIDAD FROM FLOPANICMA.FUNCIONALIDAD WHERE DESCRIPCION ='COMPRA DE BONOS')),
	(@ID_ROL,(SELECT ID_FUNCIONALIDAD FROM FLOPANICMA.FUNCIONALIDAD WHERE DESCRIPCION ='PEDIR TURNO')),
	(@ID_ROL,(SELECT ID_FUNCIONALIDAD FROM FLOPANICMA.FUNCIONALIDAD WHERE DESCRIPCION ='REGISTRAR AGENDA PROFESIONAL')),
	(@ID_ROL,(SELECT ID_FUNCIONALIDAD FROM FLOPANICMA.FUNCIONALIDAD WHERE DESCRIPCION ='REGISTRAR RESULTADO'));
	
	/*FLOPANICMA.TIPO_CANCELACION*/
	INSERT INTO FLOPANICMA.TIPO_CANCELACION(DETALLE)
	VALUES
	('CANCELACION DEL PACIENTE'),
	('CANCELACION DEL PROFESIONAL UN PERIODO'),
	('CANCELACION DEL PROFESIONAL DIA ENTERO');
	
	/*USUARIO ADMINISTRADOR (TODAS LAS FUNCIONALIDADES)*/
	
	INSERT INTO FLOPANICMA.PERSONA (ID_PERSONA,NOMBRE)
	VALUES (0,'ADMINISTRADOR GENERAL');
	
	INSERT INTO FLOPANICMA.USUARIO (ID_PERSONA,USERNAME,PASSWORD)--CAMBIAR PASSWORD HSA 256
	VALUES (0,'ADMIN','w23e');

	DECLARE @ID_USUARIO INT;
	
	SELECT @ID_USUARIO=ID_USUARIO
	FROM FLOPANICMA.USUARIO 
	WHERE USERNAME = 'ADMIN';
		
	INSERT INTO USUARIO_ROL
	VALUES (@ID_USUARIO,@ID_ROL);

END;

GO

EXEC FLOPANICMA.Z_MIGRACION_INSERT_DATOS_FIJOS;

GO

/*MIGRAR AFILIADOS Y PLANES MEDICOS*/

CREATE PROCEDURE FLOPANICMA.Z_MIGRACION_AFILIADOS
AS
BEGIN
	DECLARE @MIGRA_AFILIADO_PLAN_MEDICO TABLE
	(
		NRO_DOCUMENTO NUMERIC(18,0) NULL,
		NOMBRE VARCHAR(255) NULL,
		APELLIDO VARCHAR(255) NULL,
		DIRECCION VARCHAR(255) NULL,
		TELEFONO NUMERIC(18,0) NULL,
		E_MAIL VARCHAR(255) NOT NULL DEFAULT 'SIN E-MAIL',
		F_NACIMIENTO DATETIME NULL,
		TIPO_DOCUMENTO VARCHAR(20) NOT NULL DEFAULT 'DNI',
		ID_PLAN NUMERIC(18,0) NULL,
		DESCRIPCION VARCHAR (255) NULL,
		CUOTA NUMERIC(4,2) NULL,
		COSTO_CONSULTA NUMERIC(18,0) NULL,
		COSTO_FARMACIA NUMERIC(18,0) NULL
	);
	
	INSERT INTO @MIGRA_AFILIADO_PLAN_MEDICO
	(NRO_DOCUMENTO,NOMBRE,APELLIDO,DIRECCION,TELEFONO,E_MAIL,F_NACIMIENTO,ID_PLAN,DESCRIPCION,COSTO_CONSULTA,COSTO_FARMACIA)
	SELECT DISTINCT (PACIENTE_DNI),PACIENTE_NOMBRE,PACIENTE_APELLIDO,PACIENTE_DIRECCION,PACIENTE_TELEFONO,PACIENTE_MAIL,
			PACIENTE_FECHA_NAC,PLAN_MED_CODIGO,PLAN_MED_DESCRIPCION,PLAN_MED_PRECIO_BONO_CONSULTA,PLAN_MED_PRECIO_BONO_FARMACIA
	FROM GD_ESQUEMA.MAESTRA
	WHERE PACIENTE_DNI IS NOT NULL;
	
	INSERT INTO FLOPANICMA.PERSONA
	(ID_PERSONA,NOMBRE,APELLIDO,DIRECCION,TELEFONO,E_MAIL,F_NACIMIENTO,NRO_DOCUMENTO)
	SELECT NEXT VALUE FOR FLOPANICMA.PERSONA_SEQ, NOMBRE,APELLIDO,DIRECCION,TELEFONO,E_MAIL,F_NACIMIENTO,NRO_DOCUMENTO 
	FROM @MIGRA_AFILIADO_PLAN_MEDICO;
	
	INSERT INTO FLOPANICMA.PLAN_MEDICO
	(ID_PLAN,DESCRIPCION,COSTO_CONSULTA,COSTO_FARMACIA)
	SELECT DISTINCT (ID_PLAN),DESCRIPCION,COSTO_CONSULTA,COSTO_FARMACIA
	FROM @MIGRA_AFILIADO_PLAN_MEDICO;
	
	INSERT INTO FLOPANICMA.AFILIADO --MODIFICAR!!!!!!!!!!!! FALTA NUMERO DE CONSULTA
	(ID_AFILIADO,PLAN_MEDICO,ID_PERSONA)
	SELECT NEXT VALUE FOR FLOPANICMA.AFILIADO_SEQ, ID_PLAN,ID_PERSONA
	FROM @MIGRA_AFILIADO_PLAN_MEDICO AS TEMPTAB JOIN FLOPANICMA.PERSONA AS PERSONA ON TEMPTAB.NRO_DOCUMENTO=PERSONA.NRO_DOCUMENTO;

END;
GO

EXEC FLOPANICMA.Z_MIGRACION_AFILIADOS;
		
GO

/*MIGRAR PROFESIONALES*/

CREATE PROCEDURE FLOPANICMA.Z_MIGRACION_PROFESIONALES
AS
BEGIN
	
	DECLARE @MIGRA_PROFESIONAL TABLE
	(
		NOMBRE VARCHAR(255),
		APELLIDO VARCHAR(255),
		NRO_DOCUMENTO NUMERIC(18,0),
		DIRECCION VARCHAR(255),
		TELEFONO NUMERIC(18,0),
		E_MAIL VARCHAR(255),
		F_NACIMIENTO DATETIME
	);
	
	INSERT INTO @MIGRA_PROFESIONAL
	(NRO_DOCUMENTO,NOMBRE,APELLIDO,DIRECCION,TELEFONO,E_MAIL,F_NACIMIENTO)
	SELECT DISTINCT(MEDICO_DNI),MEDICO_NOMBRE,MEDICO_APELLIDO,MEDICO_DIRECCION,MEDICO_TELEFONO,MEDICO_MAIL,MEDICO_FECHA_NAC
	FROM GD_ESQUEMA.MAESTRA
	WHERE MEDICO_DNI IS NOT NULL;
	
	INSERT INTO FLOPANICMA.PERSONA
	(ID_PERSONA,NOMBRE,APELLIDO,DIRECCION,NRO_DOCUMENTO,TELEFONO,E_MAIL,F_NACIMIENTO)
	SELECT NEXT VALUE FOR FLOPANICMA.PERSONA_SEQ, NOMBRE,APELLIDO,DIRECCION,NRO_DOCUMENTO,TELEFONO,E_MAIL,F_NACIMIENTO
	FROM @MIGRA_PROFESIONAL;
	
	INSERT INTO FLOPANICMA.PROFESIONAL
	(ID_PERSONA,MATRICULA)
	SELECT ID_PERSONA,NEXT VALUE FOR FLOPANICMA.MATRICULA_SEQ
	FROM @MIGRA_PROFESIONAL AS TABTEMP JOIN FLOPANICMA.PERSONA AS PERSONA ON (PERSONA.NRO_DOCUMENTO=TABTEMP.NRO_DOCUMENTO);
	
END;

GO

EXEC FLOPANICMA.Z_MIGRACION_PROFESIONALES

GO
/*MIGRAR ESPECIALIDADES, TIPOS DE ESPECIALIDAD Y ESPECIALIDAD_PROFESIONAL*/

CREATE PROCEDURE FLOPANICMA.Z_MIGRACION_ESPECIALIDADES
AS
BEGIN
	DECLARE @MIGRA_ESPECIALIDADES TABLE
	(
		ID_ESPECIALIDAD NUMERIC(18,0),
		ESP_DETALLE VARCHAR(255),
		ID_TIPO_ESPECIALIDAD NUMERIC(18,0),
		TIPO_ESP_DETALLE VARCHAR(255)
	);
	
	INSERT INTO @MIGRA_ESPECIALIDADES
	(ID_ESPECIALIDAD,ESP_DETALLE,ID_TIPO_ESPECIALIDAD,TIPO_ESP_DETALLE)
	SELECT DISTINCT(ESPECIALIDAD_CODIGO),ESPECIALIDAD_DESCRIPCION,TIPO_ESPECIALIDAD_CODIGO,TIPO_ESPECIALIDAD_DESCRIPCION
	FROM GD_ESQUEMA.MAESTRA;

	INSERT INTO FLOPANICMA.TIPO_ESPECIALIDAD
	(ID_TIPO_ESPECIALIDAD,DETALLE)
	SELECT DISTINCT(ID_TIPO_ESPECIALIDAD),TIPO_ESP_DETALLE
	FROM @MIGRA_ESPECIALIDADES
	WHERE ID_TIPO_ESPECIALIDAD IS NOT NULL;
	
	INSERT INTO FLOPANICMA.ESPECIALIDAD
	(ID_ESPECIALIDAD,ID_TIPO_ESPECIALIDAD,DETALLE)
	SELECT DISTINCT(ID_ESPECIALIDAD),ID_TIPO_ESPECIALIDAD,ESP_DETALLE
	FROM @MIGRA_ESPECIALIDADES
	WHERE ID_ESPECIALIDAD IS NOT NULL;
	
	INSERT INTO FLOPANICMA.ESPECIALIDAD_PROFESIONAL
	(ID_PROFESIONAL,ID_ESPECIALIDAD)
	SELECT DISTINCT FLOPANICMA.PROFESIONAL.ID_PROFESIONAL,GD_ESQUEMA.MAESTRA.ESPECIALIDAD_CODIGO
	FROM FLOPANICMA.PERSONA JOIN
         FLOPANICMA.PROFESIONAL ON FLOPANICMA.PERSONA.ID_PERSONA = FLOPANICMA.PROFESIONAL.ID_PERSONA JOIN
         gd_esquema.Maestra ON FLOPANICMA.PERSONA.NRO_DOCUMENTO = gd_esquema.Maestra.Medico_Dni;
END;

GO

EXEC FLOPANICMA.Z_MIGRACION_ESPECIALIDADES;

GO

/*CREAR USUARIOS*/

/*CREATE PROCEDURE FLOPANICMA.Z_CREACION_USUARIOS
AS
BEGIN
	
	DECLARE @ID_ROL INT;
	
	--PROFESIONALES
	
	SELECT @ROL=ID 
	FROM FLOPANICMA.ROL
	WHERE DESCRIPCION='PROFESIONAL';
	
	INSERT INTO FLOPANICMA.USUARIOS
	(ID_PERSONA,USERNAME,PASSWORD)
	SELECT ID_PERSONA,
	
END;

GO

EXEC FLOPANICMA.Z_CREACION_USUARIOS;

GO */


/*FLOPANICMA.MIGRAR_CONSULTAS*/



/***********/
/* TRIGGERS */
/***********/



/******************/
/* ABMs y Filtros */
/******************/

